### ISSUE TITLE
Got ConnectionRefusedError

### ISSUE THREAD

**Issue by HyungJunNoh** [facebookresearch/pytorch_GAN_zoo#136]
Hello. Thank you for sharing your code!
I'm trying to run a code with CelebA data on PGAN.
After `python datasets.py celebaHQ $PATH_TO_CELEBAHQ -o $OUTPUT_DATASET - f`, I've tried to train the model by
`python train.py PGAN -c config_celeba_cropped.json --restart -n celeba_cropped`
but I got error as

Setting up a new session...
Exception in user code:

Traceback (most recent call last):
  File "/home/hhui/pytorch_GAN_zoo/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/hhui/pytorch_GAN_zoo/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/hhui/pytorch_GAN_zoo/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

......

Does anyone have same error message? Can somebody help me!! I have no idea how to deal with this.

Thank you.

**Comment by mhaines94108** [comment]
Yep, happened to me, too.

You can make it go away by adding --no_vis on the command line when you invoke the trainer.
