### ISSUE TITLE
imresize is deprecated

### ISSUE THREAD

**Issue by ivder** [facebookresearch/pytorch_GAN_zoo#90]
Hi, when I executed `train.py` I got the following error related to `imresize`. I'm using newest version of Scipy (1.3.3) and `imresize` has been removed since 1.3.0, refer to https://stackoverflow.com/questions/56204985/how-to-fix-scipy-misc-has-no-attribute-imresize. 

```
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    GANTrainer.train()
  File "/ssd/gan/pytorch_GAN_zoo/models/trainer/progressive_gan_trainer.py", line 237, in train
    maxIter=self.modelConfig.maxIterAtScale[scale])
  File "/ssd/gan/pytorch_GAN_zoo/models/trainer/gan_trainer.py", line 470, in trainOnEpoch
    for item, data in enumerate(dbLoader, 0):
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ivan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ssd/gan/pytorch_GAN_zoo/models/datasets/attrib_dataset.py", line 216, in __getitem__
    img = self.transform(img)
  File "/home/ivan/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/ssd/gan/pytorch_GAN_zoo/models/utils/image_transform.py", line 32, in __call__
    return scipy.misc.imresize(img, self.size, interp='bilinear')
AttributeError: module 'scipy.misc' has no attribute 'imresize'
```

**Comment by ivder** [comment]
Downgrading scipy is a solution, but fixing the code would be better
